### ISSUE TITLE
Please detail the instructions and upload the checkpoint

### ISSUE THREAD

**Issue by zhouxincheng** [circlePi/knowledge-driven-dialogue-lic2019#1]
As the title said, thanks.

**Comment by circlePi** [comment]
Thanks for your attention. I‘m working on it, but there are some other issues also waiting for me.

**Comment by zhouxincheng** [comment]
thanks, I'm waiting for it.

**Comment by wanglu1112** [comment]
waitting for it, too

**Comment by circlePi** [comment]
@zhouxincheng @wanglu1112 Boys, today I take it a great step forward, please check.

**Comment by zhouxincheng** [comment]
good for you
